Creating new tests for vacuum and puzzle8
Insper/ai_code pull request #1
Opened 2022-09-20 14:15 UTC by slimkaki

**Creation of new tests:**

- Puzzle8 (_test_8Puzzle.py_):
      - Adding "test_tabuleiro_invertido", which is solvable, but the map is flipped, so it will take a lot of actions to solve it.

- Vacuum World Generic (_test_VacuumWorldGeneric.py_):
      - Adding "test_profundidade_xadrez", which should take at least 25 actions to solve;
      - Adding "test_profundidade_corners", which should be solved in at least 15 actions;

2022-09-21 20:19 UTC, fbarth requested changes
por favor, modificar o que foi solicitado e reenviar.

2022-09-21 20:19 UTC, fbarth commented on src/test_8Puzzle.py
>  def test_facil():
para este tipo de problema sempre existem mais do que uma solução. codificar uma única solução com assert faz com que o teste seja incompleto. é necessário validar mais de uma solução ou utilizar algum outro critério para verificar se a solução está correta.

2022-09-22 13:25 UTC, slimkaki commented on src/test_8Puzzle.py
>  def test_facil():
corrigido!

2022-09-26 20:44 UTC, fbarth approved these changes

2022-09-26 20:44 UTC, merged