testes para Map.py
Insper/ai_code pull request #4
Opened 2022-09-20 14:31 UTC by BrunoFNRodrigues

Adiciona 3 testes para o Map.py, pois não possui nenhum; os testes validam a resposta do agente autônomo para os caminhas de i até x, l até o, p até x, validando por custo da solução.

Os testes procuram validar as respostas para caminhos longos, pois possuem mais opções de rota e são melhores para observar se heurísticas estão funcionando corretamente

2022-09-22 13:26 UTC, fbarth requested changes

2022-09-22 13:26 UTC, fbarth commented on src/test_MenorCaminho.py
> +from unittest import result
acredito que este import e desnecessario.

2022-09-22 13:27 UTC, fbarth commented
o nome do arquivo de teste também poderia ser melhor. algo como test_MapaMenorCaminho.py. o que acha?

2022-09-27 14:19 UTC, BrunoFNRodrigues commented
No commit 5c15e71378b86eceaf032fb5dcac9d6e2c013bb5 foi corrigido o nome do arquivo para um mais significativo

2022-09-27 14:22 UTC, fbarth approved these changes

2022-09-27 14:23 UTC, merged